language: "perl"
perl:
#    - "5.10"
    - "5.14"
install: "echo"
before_script:
    - sudo apt-get update
    - sudo apt-get install libffi-dev libicu-dev libgmp3-dev clang zlib1g-dev
    # No, we are not going to run the tests for all these dependencies on every commit
    - cpanm -n LWP::UserAgent TAP::Harness::Archive TAP::Harness::ReportByDescription Test::Perl::Critic
    - gcc --version
    - g++ --version
    - clang --version
# This stuff used to be required, but was rolled into the Travis CI perl support.
#    - curl -L http://cpanmin.us | sudo perl - --self-upgrade
#    - export CI_USER=$USER
#    - mkdir ~/perl5 && perl -Mlocal::lib >> /tmp/local_lib_junk.sh && source /tmp/local_lib_junk.sh
#    - sudo chown -R $CI_USER ~/.cpanm
#    - sudo chown -R $CI_USER ~/perl5

# Don't run Configure.pl tests, for now
#script: "perl Configure.pl --test=build $PARROT_CONFIG_ARGS $PARROT_OPTIMIZE --cc=\"$CC\" --link=\"$CC\" --ld=\"$CC\" --ccflags='-g' ; make $PARROT_TEST"

script: "perl Configure.pl $PARROT_CONFIG_ARGS $PARROT_OPTIMIZE --cc=\"$CC\" --link=\"$CC\" --ld=\"$CC\"; make $PARROT_TEST"

branches:
  only:
    - master
    - /smoke-me/

notifications:
  recipients:
    - parrot-ci@lists.parrot.org
  email:
    on_success: change
    on_failure: always
  irc: "irc.parrot.org#parrot"

env:
  matrix:
    # use --optimize for most since it's stable and runs fastest
    - PARROT_CONFIG_ARGS="" PARROT_OPTIMIZE="--optimize"  PARROT_TEST="smoke"  CC="clang"
    - PARROT_CONFIG_ARGS="--without-gettext --without-gmp --without-libffi --without-extra-nci-thunks --without-opengl --without-readline --without-pcre --without-zlib --without-threads --without-icu" PARROT_OPTIMIZE="" PARROT_TEST="smoke" CC="clang"
    - PARROT_CONFIG_ARGS="" PARROT_OPTIMIZE="--optimize"  PARROT_TEST="smoke"  CC="gcc"
    - PARROT_CONFIG_ARGS="--without-gettext --without-gmp --without-libffi --without-extra-nci-thunks --without-opengl --without-readline --without-pcre --without-zlib --without-threads --without-icu" PARROT_OPTIMIZE="" PARROT_TEST="smoke" CC="gcc"
    - PARROT_CONFIG_ARGS="" PARROT_OPTIMIZE="--optimize"  PARROT_TEST="smoke"  CC="g++"
    - PARROT_CONFIG_ARGS="" PARROT_OPTIMIZE="--optimize"  PARROT_TEST="testO2" CC="clang"
    # Use clang to run our coding standard and manifest tests, because it is the fastest
    # These will cause Travis to report a build failure when somebody breaks the manifest
    # tests by forgetting to add files to our manifest, or when they break our coding standards.
    # The reason we do not use smolder_fulltest is because it will intermittently trigger
    # the Travis CI time-out of 15 minutes.
    - PARROT_CONFIG_ARGS="" PARROT_OPTIMIZE="--optimize"  PARROT_TEST="codingstd_tests" CC="clang"
    - PARROT_CONFIG_ARGS="" PARROT_OPTIMIZE="--optimize"  PARROT_TEST="manifest_tests"  CC="clang"

matrix:
  allow_failures:
    - env: PARROT_CONFIG_ARGS="" PARROT_OPTIMIZE="--optimize"  PARROT_TEST="codingstd_tests" CC="clang"
