before_script:
    - sudo apt-get install ccache libffi-dev libicu-dev libgmp3-dev clang liblocal-lib-perl zlib1g-dev
    - curl -L http://cpanmin.us | sudo perl - --self-upgrade
    - export CI_USER=$USER
    - env
    - sudo chown -R $CI_USER ~/.cpanm
    - cpanm TAP::Harness::Archive TAP::Harness::Multiple TAP::Harness::ReportByDescription
script: "perl Configure.pl --test=build $PARROT_OPTIMIZE --cc=\"$CC\" --link=\"$CC\" --ld=\"$CC\" --ccflags='-g' && make $PARROT_TEST"
# branches:
#   only:
#     - master
notifications:
  recipients:
    - duke@leto.net
  email:
    on_success: change
    on_failure: always
env:
    - PARROT_OPTIMIZE="--optimize" PARROT_TEST="smolder_fulltest" CC="clang"
    - PARROT_OPTIMIZE=""           PARROT_TEST="smolder_fulltest" CC="clang"
    - PARROT_OPTIMIZE="--optimize" PARROT_TEST="smolder_fulltest" CC="ccache gcc"
    - PARROT_OPTIMIZE="--optimize" PARROT_TEST="smolder_fulltest" CC="ccache g++"
    - PARROT_OPTIMIZE="--optimize" PARROT_TEST="smolder_fulltest" CC="gcc"
    - PARROT_OPTIMIZE="--optimize" PARROT_TEST="smolder_fulltest" CC="g++"
    - PARROT_OPTIMIZE=""           PARROT_TEST="smolder_fulltest" CC="ccache gcc"
    - PARROT_OPTIMIZE=""           PARROT_TEST="smolder_fulltest" CC="ccache g++"
    - PARROT_OPTIMIZE=""           PARROT_TEST="smolder_fulltest" CC="gcc"
    - PARROT_OPTIMIZE=""           PARROT_TEST="smolder_fulltest" CC="g++"
